apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-postgres-exporter
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-postgres-exporter-2.5.0
    heritage: Helm
    release: postgresql-expoter
  name: postgresql-expoter-prometheus-postgres-exporter
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-postgres-exporter
      release: postgresql-expoter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus-postgres-exporter
        release: postgresql-expoter
    spec:
      containers:
      - name: prometheus-postgres-exporter
        env:
        - name: DATA_SOURCE_URI
          value: #POSTGRESQL_SERVER_URI#:5432/postgres?sslmode=disable
        - name: DATA_SOURCE_USER
          value: #USER_NAME#
        - name: DATA_SOURCE_PASS
          value: #PASSWORD#
        image: pamir/postgres-exporter-linux-amd64:master
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1

        ports:
        - containerPort: 9187
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
